trigger:
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest
variables:
- group: archie-app-deployment
- name: tag_id
  value: $(Build.BuildId)
stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        script: echo "this works"
    - task: Docker@2
      inputs:
        containerRegistry: 'archieacr-sc'
        repository: $(reponame)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag_id)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: Bash@3
      inputs:
        targetType: inline
        script: echo "the contents of the target directory after copy are"; ls -lRt $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'